
compiler:
  solc:
    version: 0.8.4
#     remappings:
#       - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.2.0"
#       - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
#       - "@chainlink=smartcontractkit/chainlink/tree/develop/contracts/src/v0.8/"
#       - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.0.2'
#       # - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.0.2'

# dependencies:
#   - OpenZeppelin/openzeppelin-contracts@4.2.0
#   - OpenZeppelin/openzeppelin-contracts-upgradeable@4.2.0
#   # - smartcontractkit/chainlink-brownie-contracts@1.0.2
